@startuml

hide footbox
autonumber

participant "camiaoRoute:CamiaoRoute" as route
participant "camiaoController:CamiaoController" as controller
participant "camiaoService:CamiaoService" as service
participant "truckRepo: CamiaoRepo" as repo


?o-> route : GET(.../api/camiao/camioesExistentes)
activate route
route -> controller: listarCamioes()
activate controller
controller -> service : listarCamioes()
activate service
service -> repo : findAll()
activate repo
repo --> service : successList
deactivate repo
service --> controller: successList
deactivate service
controller --> route: successList
<-- route : successList
?o-> route : PUT(.../api/camiao/editar)
route -> controller: editarCamiao(camiao)
controller -> service : editarCamiao(camiao)
activate service
service -> repo : save(camiao)
activate repo
repo --> service : successEdit
deactivate repo
service --> controller: successEdit
deactivate service
controller --> route: successEdit
deactivate controller
<-- route : successEdit
deactivate route

@enduml