@startuml

actor "Gestor de Logística" as gl

participant "<<System (C4)>>\nEletricGo" as c4

activate gl
gl -> c4: Inicia o processo de planeamento de uma rota
activate c4
c4 --> gl: Solicita os dados necessários (data e algoritmo)
deactivate c4
gl -> c4 : Introduz os dados solicitados
activate c4
c4 --> gl : Informa o sucesso da operação
deactivate c4
deactivate gl


@enduml