@startuml

actor "Gestor de Logística" as gl

participant "<<System (C4)>>\nEletricGo" as c4

activate gl
gl -> c4: Listar Viagens
activate c4
c4 --> gl: Solicita os dados
deactivate c4
gl -> c4 : Introduz os dados solicitados
activate c4
c4 --> gl : Solicita a confirmação dos dados
deactivate c4
gl -> c4 : Confirma os dados
activate c4
c4 --> gl : Informa o sucesso da operação
deactivate c4
deactivate gl


@enduml