@startuml

actor "Gestor de Frota" as gestor

participant "<<System (C4)>>\nEletricGo" as c4

activate gestor
gestor -> c4: Inicia o processo de edição do camião
activate c4
c4 --> gestor: Solicita os dados necessários para a edição
deactivate c4
gestor -> c4 : Introduz os dados solicitados
activate c4
c4 --> gestor : Solicita a confirmação dos dados da edição
deactivate c4
gestor -> c4 : Confirma os dados da edição
activate c4
c4 --> gestor : Informa o sucesso da operação
deactivate c4
deactivate gestor
@enduml