@startuml
autonumber

actor "Gestor de Armazém" as gestor
participant "<<System (C4)>>\nVisualização" as SYSTEM
participant "<<System (C4)>>\nMDA" as SYSTEM2

activate gestor
gestor -> SYSTEM:  Listar Entregas
activate SYSTEM
SYSTEM --> gestor: Solicita os dados necessários
deactivate SYSTEM
gestor -> SYSTEM : Introduz os dados solicitados
activate SYSTEM 
SYSTEM --> gestor: Solicita a confirmação dos dados 
deactivate SYSTEM
gestor -> SYSTEM : Confirma os dados 
activate SYSTEM 
SYSTEM -> SYSTEM2 : GET listarEntregas
activate SYSTEM2
SYSTEM2 --> SYSTEM : entregas (JSON)
deactivate SYSTEM2
SYSTEM --> gestor: Apresenta a informação pedida
deactivate SYSTEM
deactivate gestor

@enduml